### ISSUE TITLE
Filtering is broken

### ISSUE THREAD

**Issue by JohnMoehrke** [FHIR/ig-registry#109]
since the new feature to add test servers and source servers... the filtering is broken. 

For example,  selecting "IHE" publisher gives you zero results.  and then unselecting "IHE" does not give you anything different. Not specific to IHE.

does not work for Authority, Country, Release, or Category.

Note that "Contents" seems to work.

**Comment by JohnMoehrke** [comment]
@grahamegrieve

**Comment by grahamegrieve** [comment]
fixed
