### ISSUE TITLE
Creating & Publishing FHIR Packages page is out-of-date

### ISSUE THREAD

**Issue by JohnMoehrke** [FHIR/ig-registry#96]
This page
    https://registry.fhir.org/submit

does not mention the http://registry.fhir.org registry, or how to use it.

**Comment by grahamegrieve** [comment]
I'm closing this because it's not related to this git repo

**Comment by wardweistra** [comment]
@JohnMoehrke Indeed, there's only information on publishing packages on there. Is the information you expected on this page: https://confluence.hl7.org/display/FHIR/FHIR+Package+Registry+User+Documentation ?

This is linked from the footer and written by David Hay.

You can report Registry issues on https://jira.hl7.org/secure/RapidBoard.jspa?rapidView=48&projectKey=HSCR (with component = FHIR Registry)
